- name: novaapi config file
  template:
    src: "{{ item }}.conf.j2"
    dest: "/etc/{{ item }}/{{ item }}.conf"
  with_items:
    - "nova"
  register: novaconfig
  when: inventory_hostname in groups.novaapi_hosts

