---
# tasks file for os-neutrons
#- include: neutronsDB.yml
#- include: neutronsUser.yml
#  when: inventory_hostname == groups.keystone_hosts[0]
#- include: neutronsService.yml
#  when: inventory_hostname == groups.keystone_hosts[0]
#- include: neutronsEndpoints.yml
#  when: inventory_hostname == groups.keystone_hosts[0]
- include: neutronaPackages.yml
  when: inventory_hostname in groups.neutrona_hosts
- include: neutronaConfigFile.yml
  when: inventory_hostname in groups.neutrona_hosts
- include: createML2link.yml
  when: inventory_hostname in groups.neutrons_hosts
- include: neutronaInitDB.yml
  when: inventory_hostname == groups.neutrona_hosts[0]
- include: novaapiServiceStart.yml
  when: inventory_hostname in groups.novaapi_hosts
- include: neutronsServiceStart.yml
  when: inventory_hostname in groups.neutrons_hosts
- include: neutronaServiceStart.yml
  when: inventory_hostname in groups.neutrona_hosts
