- name: start neutron-server
  service: name=neutron-server state=restarted enabled=yes
  when: inventory_hostname in groups.neutrons_hosts and neutronconfig.changed

- name: start neutron-linuxbridge-agent
  service: name=neutron-linuxbridge-agent state=restarted enabled=yes
  when: inventory_hostname in groups.neutrons_hosts and neutronconfig.changed

#- name: start nova-consoleauth
#  service: name=openstack-nova-consoleauth state=restarted enabled=yes
#  when: inventory_hostname in groups.neutrons_hosts and neutronconfig.changed
#
#- name: start nova-scheduler
#  service: name=openstack-nova-scheduler state=restarted enabled=yes
#  when: inventory_hostname in groups.neutrons_hosts and neutronconfig.changed
#
#- name: start nova-conductor
#  service: name=openstack-nova-conductor state=restarted enabled=yes
#  when: inventory_hostname in groups.neutrons_hosts and neutronconfig.changed
#
#- name: start nova-novncproxy
#  service: name=openstack-nova-novncproxy state=restarted enabled=yes
#  when: inventory_hostname in groups.neutrons_hosts and neutronconfig.changed
