
- name: start neutron-linuxbridge-agent
  service: name=neutron-linuxbridge-agent state=started enabled=yes
  when: inventory_hostname in groups.neutrona_hosts 

- name: start neutron-dhcp-agent
  service: name=neutron-dhcp-agent state=started enabled=yes
  when: inventory_hostname in groups.neutrona_hosts

- name: start neutron-metadata-agent
  service: name=neutron-metadata-agent state=started enabled=yes
  when: inventory_hostname in groups.neutrona_hosts 

- name: start neutron-l3-agent
  service: name=neutron-l3-agent state=started enabled=yes
  when: inventory_hostname in groups.neutrona_hosts 

- name: start neutron-linuxbridge-agent
  service: name=neutron-linuxbridge-agent state=restarted enabled=yes
  when: inventory_hostname in groups.neutrona_hosts and neutronconfig.changed

- name: start neutron-dhcp-agent
  service: name=neutron-dhcp-agent state=restarted enabled=yes
  when: inventory_hostname in groups.neutrona_hosts and neutronconfig.changed

- name: start neutron-metadata-agent
  service: name=neutron-metadata-agent state=restarted enabled=yes
  when: inventory_hostname in groups.neutrona_hosts and neutronconfig.changed

- name: start neutron-l3-agent
  service: name=neutron-l3-agent state=restarted enabled=yes
  when: inventory_hostname in groups.neutrona_hosts and neutronconfig.changed
