---
# tasks file for os-neutron-compute
- include: neutron-computePackages.yml 
  when: inventory_hostname in groups.novacompute_hosts
- include: neutron-computeConfigFile.yml
  when: inventory_hostname in groups.novacompute_hosts
- include: createML2link.yml
  when: inventory_hostname in groups.novacompute_hosts
- include: neutron-computeServiceStart.yml 
  when: inventory_hostname in groups.novacompute_hosts
  
