- name: neutron config file
  template:
    src: "{{ item }}.conf.j2"
    dest: "/etc/{{ item }}/{{ item }}.conf"
  with_items:
    - "neutron"
  register: neutroncomputeconfig
  when: inventory_hostname in groups.novacompute_hosts

- name: neutron linuxbridge_agent.ini file
  template:
    src: "{{ item }}.ini.j2"
    dest: "/etc/neutron/plugins/ml2/{{ item }}.ini"
  with_items:
    - "linuxbridge_agent"
  register: neutroncomputeconfig
  when: inventory_hostname in groups.novacompute_hosts
