---
# Handlers for MariaDB

- name: restart mysql
  service: name=mysqld state=restarted

- name: start mysql
  service: name=mysqld state=started

- name: stop mysql
  service: name=mysqld state=stopped


