---
# tasks file for ../roles/os-keystone
- include: keystoneDB.yml
- include: packages.yml
- include: configfile.yml
- include: initdb.yml
- include: httpdconfig.yml
- include: keystone_service.yml
  when: inventory_hostname == groups.keystone_hosts[0]
