# Create a service
- name: Ensure Nova Service
  keystone:
    command: "ensure_service"
    token: "{{ keystone_auth_admin_token }}"
    endpoint: "{{ keystone_service_adminurl }}"
    service_name: "{{ nova_service_name }}"
    service_type: "{{ nova_service_type }}"
    description: "{{ nova_service_description }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
  register: add_service
  until: add_service|success
  retries: 2
  delay: 1
  tags:
    - nova-api-setup
    - nova-service-add
    - nova-setup

