# Create an endpoint
- name: Ensure Nova Endpoint
  keystone:
    command: "ensure_endpoint"
    token: "{{ keystone_auth_admin_token }}"
    endpoint: "{{ keystone_service_adminurl }}"
    region_name: "{{ nova_service_region }}"
    service_name: "{{ nova_service_name }}"
    service_type: "{{ nova_service_type }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
    endpoint_list:
      - url: "{{ nova_service_publicurl }}"
        interface: "public"
      - url: "{{ nova_service_adminurl }}"
        interface: "admin"
      - url: "{{ nova_service_internalurl }}"
        interface: "internal"
  register: add_service
  until: add_service|success
  retries: 2
  delay: 1
  tags:
    - nova-api-setup
    - nova-service-add
    - nova-setup

