# Create an endpoint
- name: Ensure Neutron Endpoint
  keystone:
    command: "ensure_endpoint"
    token: "{{ keystone_auth_admin_token }}"
    endpoint: "{{ keystone_service_adminurl }}"
    region_name: "{{ neutron_service_region }}"
    service_name: "{{ neutron_service_name }}"
    service_type: "{{ neutron_service_type }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
    endpoint_list:
      - url: "{{ neutron_service_publicurl }}"
        interface: "public"
      - url: "{{ neutron_service_adminurl }}"
        interface: "admin"
      - url: "{{ neutron_service_internalurl }}"
        interface: "internal"
  register: add_service
  until: add_service|success
  retries: 2
  delay: 1
  tags:
    - neutron-api-setup
    - neutron-service-add
    - neutron-setup

