# Create an neutron tenant
#- name: Ensure neutron tenant
#  keystone:
#    command: "ensure_tenant"
#    token: "{{ keystone_auth_admin_token }}"
#    endpoint: "{{ keystone_service_adminurl }}"
#    tenant_name: "{{ keystone_neutron_tenant_name }}"
#    description: "{{ keystone_neutron_description }}"
#    insecure: "{{ keystone_service_adminuri_insecure }}"
#  register: add_service
#  until: add_service|success
#  retries: 1
#  delay: 1
#  tags:
#    - neutron-api-setup
#    - neutron-setup

# Create an neutron user
- name: Ensure Neutron user
  keystone:
    command: "ensure_user"
    token: "{{ keystone_auth_admin_token }}"
    endpoint: "{{ keystone_service_adminurl }}"
    user_name: "{{ keystone_neutron_user_name }}"
    tenant_name: "{{ keystone_neutron_tenant_name }}"
    password: "{{ keystone_auth_neutron_password }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
  register: add_service
  until: add_service|success
  retries: 2
  delay: 1
  tags:
    - neutron-api-setup
    - neutron-setup

# Add a role to the user
- name: Ensure neutron user to Admin role
  keystone:
    command: "ensure_user_role"
    token: "{{ keystone_auth_admin_token }}"
    endpoint: "{{ keystone_service_adminurl }}"
    user_name: "{{ keystone_neutron_user_name }}"
    tenant_name: "{{ keystone_neutron_tenant_name }}"
    role_name: "{{ neutron_role_name }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
  register: add_service
  until: add_service|success
  retries: 2
  delay: 1
  tags:
    - neutron-api-setup
    - neutron-setup

# Add the default user role
- name: Ensure default neutron user role
  keystone:
    command: "ensure_role"
    token: "{{ keystone_auth_admin_token }}"
    endpoint: "{{ keystone_service_adminurl }}"
    role_name: "{{ neutron_default_role_name }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
  register: add_member_role
  until: add_member_role|success
  retries: 2
  delay: 1
  tags:
    - neutron-api-setup
    - neutron-setup


