# Create a service
- name: Ensure Neutron Service
  keystone:
    command: "ensure_service"
    token: "{{ keystone_auth_admin_token }}"
    endpoint: "{{ keystone_service_adminurl }}"
    service_name: "{{ neutron_service_name }}"
    service_type: "{{ neutron_service_type }}"
    description: "{{ neutron_service_description }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
  register: add_service
  until: add_service|success
  retries: 2
  delay: 1
  tags:
    - neutron-api-setup
    - neutron-service-add
    - neutron-setup

