- name: neutron config file
  template:
    src: "{{ item }}.conf.j2"
    dest: "/etc/{{ item }}/{{ item }}.conf"
  with_items:
    - "neutron"
  when: inventory_hostname in groups.neutrons_hosts
  register: neutronconfig

- name: neutron ml2_conf.ini file
  template:
    src: "{{ item }}.ini.j2"
    dest: "/etc/neutron/plugins/ml2/{{ item }}.ini"
  with_items:
    - "ml2_conf"
  when: inventory_hostname in groups.neutrons_hosts
  register: neutronconfig

