- name: start libvirtd
  service: name=libvirtd state=started enabled=yes
  when: inventory_hostname in groups.novacompute_hosts

- name: start nova-compute
  service: name=openstack-nova-compute state=started enabled=yes
  when: inventory_hostname in groups.novacompute_hosts

