- name: install openstack repo 
  yum: name=centos-release-openstack-liberty state=installed
  tags:
    - nova-compute-setup
    - nova-compute-packages

- name: install nova compute packages
  yum: name={{ item }} state=installed
  with_items:
    - openstack-nova-compute
    - sysfsutils
    - libvirt-daemon
  tags:
    - nova-compute-setup
    - nova-compute-packages
