- name: novacompute config file
  template:
    src: "{{ item }}.conf.j2"
    dest: "/etc/{{ item }}/{{ item }}.conf"
  with_items:
    - "nova"
  register: nova_compute_config
  when: inventory_hostname in groups.novacompute_hosts

