
- hosts: 
    - galera_hosts
    - haproxy_hosts
    - rabbitmq_hosts
    - keystone_hosts
    - glance_hosts
    - novaapi_hosts
    - neutrons_hosts
  vars:
    - enable_mariadb: true
    - master: cntrl1
    - enable_rabbitmq: true
    - enable_keystone: true
    - enable_glance: true
    - enable_novaapi: true
    - enable_neutron: true
    - nova_console: "novnc"
  roles:
    - ../roles/haproxy


