# Create a service
- name: Ensure Glance Service
  keystone:
    command: "ensure_service"
    token: "{{ keystone_auth_admin_token }}"
    endpoint: "{{ keystone_service_adminurl }}"
    service_name: "{{ glance_service_name }}"
    service_type: "{{ glance_service_type }}"
    description: "{{ glance_service_description }}"
    insecure: "{{ keystone_service_adminuri_insecure }}"
  register: add_service
  until: add_service|success
  retries: 2
  delay: 1
  tags:
    - glance-api-setup
    - glance-service-add
    - glance-setup

