- name: install openstack repo 
  yum: name=centos-release-openstack-liberty state=installed
  tags:
    - glance-setup
    - glance-packages

- name: install glance packages
  yum: name={{ item }} state=installed
  with_items:
    - openstack-glance
    - python-glance 
    - python-glanceclient
  tags:
    - glance-setup
    - glance-packages
